name: My first workflow

on: push

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
        - name: doing a code checkout
          run: actions/checkout@master

    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome to message
          run: echo "this is a run from actions"

        - name: list files
          run: ls
          
        - name: Readme
          run: cat ./README.md