name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome to message
          run: echo "this is a run from actions"

        - name: list files
          run: ls
          
        - name: Readme
          run: cat README.md